### ISSUE TITLE
Instruction Dataset

### ISSUE THREAD

**Issue by cahya-wirawan** [ecnu-sea/SEA#4]
Hi, great paper and congratulation for being accepted in EMLNP 2024. And thanks for publishing the collected dataset. Btw, would you also publish the data that was generated by GPT4? That would be great, thanks.

**Comment by heroding77** [comment]
Thank you for your support of our work! You can find the processing reviews here: [SEA_data](https://huggingface.co/datasets/ECNU-SEA/SEA_data)

**Comment by cahya-wirawan** [comment]
Yes I have checked the zip files, it contains review_json directory with all reviews in json format from crawled raw reviews. But I think it doesn't contain the consolidated review that is generated by GPT4, does it?

**Comment by heroding77** [comment]
Hello, the ZIP file contains the review comments integrated through SEA-S, which was distilled from GPT-4's integration capabilities. If you would like to access the original review content integrated by GPT-4, you can click [here ](https://huggingface.co/datasets/ECNU-SEA/SEA_data/blob/main/GPT4_consolidated_reviews_2k.zip)to visit.

**Comment by cahya-wirawan** [comment]
Thanks for adding the original review content integrated by GPT-4
