### ISSUE TITLE
Could you please provide some instructions to use SEA-S?

### ISSUE THREAD

**Issue by DaozeZhang** [ecnu-sea/SEA#5]
Thanks for the awesome and solid work!
I noticed that you release the SEA-S and SEA-E models on HF, thanks for the contribution to the community!
Now I wanna to try using your SEA-S model to merge multiple reviews into one review. So could you please tell me the example prompt you used on SEA-S? 
Or should I just tell the model "to merge the following reviews"? If so, I still think using the prompt you have used on SEA-S would be better :)

**Comment by heroding77** [comment]
You can see the prompt in inference/template.json, have fun!

**Comment by DaozeZhang** [comment]
So I just need to concatenate the prompt in `inference/template.json` and the multiple reviews, as an entire input. And then give this input to to SEA-S. In the merge reviews operation, it is not necessary to show the content of the paper to SEA-S, right?

**Comment by heroding77** [comment]
> So I just need to concatenate the prompt in `inference/template.json` and the multiple reviews, as an entire input. And then give this input to to SEA-S. In the merge reviews operation, it is not necessary to show the content of the paper to SEA-S, right?

Right~
